version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    groups:
      main-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "Django"
          - "mysqlclient"
          - "nikkei-utils"
      dev-dependencies:
        dependency-type: "development"
