services:
  nginx:
    image: nginx:stable
    depends_on:
      - webapp
    ports:
      - "8080:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/tmp:/log"
      - "/tmp:/var/log/nginx/healthd"
    mem_limit: 64m
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "/tmp:/log"
      - "/tmp:/tmp"
    mem_reservation: 768m
    environment:
      DJANGO_SETTINGS_MODULE: bbbb.settings.local
      APP_VERSION: local
    command: uwsgi uwsgi.ini
    read_only: true
  pytest:
    profiles:
      - pytest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: bbbb.settings.local
      APP_VERSION: local
    user: root
    command: >
      bash -c "apt update &&
      apt install -y --no-install-recommends curl &&
      export POETRY_HOME=/opt/poetry &&
      curl -sSL https://install.python-poetry.org | python3 - &&
      cp pyproject.toml poetry.lock /opt/pythonenv/ &&
      cd /opt/pythonenv/ &&
      $${POETRY_HOME}/bin/poetry config virtualenvs.in-project true &&
      $${POETRY_HOME}/bin/poetry install --no-root &&
      cd /usr/src/app &&
      pytest"
